version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - dbdata6:/data/db
  front:
    image: front
    environment:
    - REACT_APP_BACKEND_URL=https://einsteinacademyapi.online
  back:
    image: back
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - JWT_SECRET=secret
    volumes:
      - ~/uploads:/app/uploads
  nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /home/ubuntu/certs:/etc/letsencrypt:ro
volumes:
  dbdata6: