version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - dbdata6:/data/db
    ports: 
    - 27017:27017 
  front:
    image: front
    ports:
      - '3001:80'
    environment:
    - REACT_APP_BACKEND_URL=http://localhost:5000
  back:
    image: back
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - JWT_SECRET=secret
    volumes:
      - ./uploads:/app/uploads
volumes:
  dbdata6: